### ISSUE TITLE
is there any problem or i am doing something very wrong ? 

### ISSUE THREAD

**Issue by Divyadeep00** [hyperspy/rosettasciio#291] opened 2024-07-03 20:58 UTC
This is my sample dafault EDX navigator 
![image](https://github.com/hyperspy/rosettasciio/assets/94546661/77236c0a-fd4e-4a36-9b69-42c262c8e562)

my data is in 280*550 pixels (viewing printing s) but why there is X up to 1.82e+04 and similarly y also. I do not have that much pixcel. 

which we can see by this image  
![image](https://github.com/hyperspy/rosettasciio/assets/94546661/02b166a2-0b0f-4a7d-864f-79a8361886af)

I would like to share my workflow, 

```
import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
s=hs.load("MS-1b_S.bcf")


```
 ` [<Signal2D, title: Video, dimensions: (|550, 284)>,
 <Signal2D, title: , dimensions: (|1205, 999)>,
 <Signal2D, title: , dimensions: (|1205, 999)>,
 <Signal2D, title: , dimensions: (|1205, 999)>,
 <EDSSEMSpectrum, title: EDX, dimensions: (550, 284|4096)>]`

```
s[4].metadata.Acquisition_instrument.SEM.beam_energy = 50
s[4].plot(xray_lines=True)


eds=p.get_lines_intensity(['Fe_Ka','Al_Ka',"Si_Ka", "Ti_Ka", "Mn_Ka","K_Ka"])
cmaps = ['Blues', 'Reds', 'Greens', 'Purples']
s_img=hs.plot.plot_images(eds, axes_decor="off", scalebar="all", cmap=cmaps, per_row=3)

Fe=eds[0].data
Al=eds[1].data
plt.imshow(Fe,cmap="Blues")
# Assuming it's RGB data
plt.show()

```
after this I notice the above error, map at the top of edx signal, please help me to run the .bcf file, my aim is I have a roi (left, right, top bottom) values  I have need sum spectrum of that area. 

when I ran 
import hyperspy.api as hs

```
import scipy
# Load your data (replace with actual data loading code)
data = hs.load('MS-1b_S.bcf')
data= data[4]
data.metadata.Acquisition_instrument.SEM.beam_energy = 50
data.plot()
roi = hs.roi.RectangularROI(left=x1, right=x2, top=y1, bottom=y2)

s_roi = roi.interactive(data, recompute_out_event=None, color='C1')
s_roi = roi(data)
roi_sum = hs.interactive(s_roi.sum, recompute_out_event=None)
roi_sum.plot()
```

above code, I got the required image, but the spectrum is down. 
![image](https://github.com/hyperspy/rosettasciio/assets/94546661/4d43fc8d-c9dc-483b-ad98-de65ff58af5d)

kindly help me, 
the drive link for my .bcf file is [this
](https://drive.google.com/drive/folders/1bMlBfi5TuyoIIVSQCxF8P3lgEPc58ljC?usp=sharing)

**Comment by ericpre** [comment] 2024-07-04 15:13
Closing as a duplicate of #290.

@Divyadeep00, please avoid open several issues on the same issue to avoid parallel discussions. Please continue the discussion at #290.

**Closed by ericpre** 2024-07-04 15:13 UTC
