### ISSUE TITLE
3.12 velox emd files not supported

### ISSUE THREAD

**Issue by DitDotz** [hyperspy/rosettasciio#242] opened 2024-03-25 13:20 UTC
#### Describe the bug
AttributeError: 'NoneType' object has no attribute 'keys' occurred when I attempted to load an emd file through hs.load('sample.emd')

#### To Reproduce
Steps to reproduce the behaviour:
```
hs.load('sample.emd')
# emd file is produced using velox 3.12
```

#### Expected behavior

For the file to be read correctly 

#### Python environement:
 - rsciio version: 0.3
 - Python version: 3.9
 - HyperSpy version: 2.0.1 (if relevant)
 - HyperSpy extensions and version used
 - Velox version: 3.12.1.5

#### Additional context
Add any other context about the problem here. If necessary, add screenshots to help explain your problem.
![Capture](https://github.com/hyperspy/rosettasciio/assets/53271140/169e59d2-e186-41f7-9430-536c1d9762ed)

**Comment by ericpre** [comment] 2024-03-25 21:00
Thank you for reporting the issue, this is already fixed and to be released soon (in a week or so),

Closing as duplicate of https://github.com/hyperspy/rosettasciio/issues/226 and fixed in https://github.com/hyperspy/rosettasciio/pull/232.

**Closed** 2024-03-25 21:00 UTC
Labels: type: bug
